### ISSUE TITLE
ML pipeline to make samples

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/open-data-pvnet#62]
## Detailed Description
Following on from #1 I wanted to write this issue. 

We currently have lots of NWP data and PVLive data. Its too much to go into memory, so we have to cut it down ready for ML experiments. The way we've done this in the past is to create samples of data. This are smaller chinks of the data, that contain specific data for a certain time (and space). These then get batched up in a dataloader and the ML model can then train from them. 

So we want to build a pipeline for making these samples (most of the work is done in ocf-data-sampler)

## Context
- NWP = numerical weather predictions data
- PVLive data, national solar generation data
- We have GFS on S3 and we have been collecting Metoffice Global data
- @jcamier @siddharth7113 and others have been working on this already
- ocf-data-sampler is python library used to create samples from large datasets. 

## Possible Implementation
There are lots of ways to do this, but theres a suggestion to use ocf-data-sampler

You start with a data configuration (TODO get example) that tells ocf-data-sampler what to load and other specific bits. 

It would be really great to
1. Create a configuration for this project. Perhaps starting with GFS and PVLive, and then adding Metoffice later
2. Using this configuration, run ocf-data-sampler and make some samples
3. Make a script for 2. so that others can use it.
4. Same samples, maybe in s3, so others can use them

The ocf-data-sampler class we recommend using is [PVNetUKRegionalDataset](https://github.com/openclimatefix/ocf-data-sampler/blob/main/ocf_data_sampler/torch_datasets/datasets/pvnet_uk.py#L172), but there are a few things that might need adding like
- [ ] GFS normalisation constants
- [ ] Make it work for gsp_id=0 (this is national)

**Comment by peterdudfield** [comment]
Example of config, not tested
```
general:
  description: Example config for producing PVNet samples
  name: example_config

input_data:
  gsp:
    # Path to GSP data in zarr format
    # e.g. gs://solar-pv-nowcasting-data/PV/GSP/v7/pv_gsp.zarr
    zarr_path: PLACEHOLDER.zarr
    interval_start_minutes: -60
    # Specified for intraday currently
    interval_end_minutes: 480
    time_resolution_minutes: 30
    # Random value from the list below will be chosen as the delay when dropout is used
    # If set to null no dropout is applied. Only values before t0 are dropped out for GSP.
    # Values after t0 are assumed as targets and cannot be dropped.
    dropout_timedeltas_minutes: null
    dropout_fraction: 0 # Fraction of samples with dropout

  nwp:
    gfs:
      provider: gfs
      # Path to UKV NWP data in zarr format
      # e.g. gs://solar-pv-nowcasting-data/NWP/UK_Met_Office/UKV_intermediate_version_7.zarr
      # n.b. It is not necessary to use multiple or any NWP data. These entries can be removed
      zarr_path: PLACEHOLDER.zarr
      interval_start_minutes: -60
      # Specified for intraday currently
      interval_end_minutes: 480
      time_resolution_minutes: 60
      channels: #TODO this need updating
        - t # 2-metre temperature
        - dswrf # downwards short-wave radiation flux
        - dlwrf # downwards long-wave radiation flux
        - hcc # high cloud cover
        - mcc # medium cloud cover
        - lcc # low cloud cover
        - sde # snow depth water equivalent
        - r # relative humidty
        - vis # visibility
        - si10 # 10-metre wind speed
        - wdir10 # 10-metre wind direction
        - prate # precipitation rate
        # These variables exist in CEDA training data but not in the live MetOffice live service
        - hcct # height of convective cloud top, meters above surface. NaN if no clouds
        - cdcb # height of lowest cloud base > 3 oktas
        - dpt # dew point temperature
        - prmsl # mean sea level pressure
        - h # geometrical? (maybe geopotential?) height
      image_size_pixels_height: 24
      image_size_pixels_width: 24
      dropout_timedeltas_minutes: [-360]
      dropout_fraction: 1.0 # Fraction of samples with dropout
      max_staleness_minutes: null
```
